---
deployment:
  tasks:
    - export DEPLOYPATH=/home/buildalx/craft.buildal.ug/templates/craft/
    - - /bin/cp -R css $DEPLOYPATH
    - - /bin/cp -R html $DEPLOYPATH
    - - /bin/cp -R acm $DEPLOYPATH
    - - /bin/cp -R etc $DEPLOYPATH
    - - /bin/cp -R js $DEPLOYPATH
    - - /bin/cp -R language $DEPLOYPATH